# Generated by Django 5.1.3 on 2024-11-24 13:28

import cloudinary.models
import django.db.models.deletion
import trainers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('first_name', models.CharField(error_messages={'invalid': 'First name must only contain alphabetic characters.'}, max_length=100, validators=[trainers.models.validate_name])),
                ('last_name', models.CharField(error_messages={'invalid': 'Last name must only contain alphabetic characters.'}, max_length=100, validators=[trainers.models.validate_name])),
                ('age', models.IntegerField(validators=[trainers.models.validate_age])),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
