# Generated by Django 5.1.4 on 2024-12-30 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainer_options_trainer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='trainerfeedback',
            index=models.Index(fields=['trainer', 'created_at'], name='trainers_tr_trainer_416479_idx'),
        ),
    ]
